{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Exceptions Handling in Python"
   ]
  },
  {
   "attachments": {
    "image.png": {
     "image/png": "iVBORw0KGgoAAAANSUhEUgAAAdYAAABtCAYAAAAcYEBYAAASo0lEQVR4Ae2dPZIcSXJGZ7kwo3HWYDTSDBKVpDJaayuuCHVUyiWPPnoegBfYC+ACe4K+AW9QR+ARlt+rzq/HNyerp9E/wwbw3MyRkR4eHpFPqA9R1RX13XeaBCQgAQlIQAISkIAEJCABCUhAAr8/gfe7Kf9td/+5t4z/tA3i+iH+Lv7DFnvqhXVOf2qdzxnHs7B+TQISkIAEJPAoAv+UrL+PzN5zfar9Rwa2JtclTuwcf6p1XdTA//bUQo8YN2v/lPyfHzHGFAlIQAISkMCFAIK1F7y/J0b8D/E/x0/x7mK781wS+68497UljR/jH+P/G8e4LvGOS/Oyc6UeuTcENmM+xuLE/zleO1on/ayv9petQR3a1KGNses8xeeumfb3Wxzhx6jH87M21rzfsVKT534fx8ihzhLf8yB+ijc3TU0CEpCABL52At0JIiw4YlBhZafG7o1dGzFEiBza5/jt1s7lIoTE13j707wX1mWLN0bOf2+xiuP/5P7T5vRPQWKdiDQCyRoq/OSxZkStYk6MdePM0WdCLOlDHPvc3Hcd1OaZibEORHWN049RnzU2n/5rPJiDOqzrFNckIAEJSOCNE+gLOgLxHGNHhwAgGHXuW5d+BJUYAtV507xYc8+5646RvIoc1yU+xxGrmCJkCFXXkeZl7o7nHmv/bdrMhQhiFU3WwQ52idOeRv4aR6hPcfpbr7ti1rDGsTme9a3xuf7cXtZ8FGcs7BBU2q2fpiYBCUhAAm+ZAC/e7Iqea9Q574rsxeGv6Se2xBGYil7FiRr004chetxj14R1ufTe7RDXrc2Yc5wru+RpR+ukv2vompbE2qYfo+ZtfN2cnWvHpXmxCmvjzIdVWJe0Z12YrPFrPNJ1L+LU1iQgAQlI4BshgIBMwZjCgsCxI8RoL/G5c5u5fds1KZfdXGtyXeJzXGMJ3wtXxRlB5T8MFTZysLlO5sWxzktNBJO3Z1kru+x3cdZ/G0cga8QZT1532R3fdXSnWWFlt0s+V6z587lakxrN63oug/xHAhKQgAS+fgJTsHjaKQ4IFWJSX9K+JiR9u5jcT/FzHKuIznGN0V/h6ryMxamDKNXa37VQ/0Oce6xt8qjZPJ4Bkew911N8X4+3wWuINXlLvOtL8/6zZvrIweZztSZMT/HOSVuTgAQkIAEJPIkA4vIUWzIIIarRZrf5kjbXVhHkOuOd7yj2mL7mcH2oxsyzLQEJSEACEngVAv0sF1FdX2WGX4oieszD7lKTgAQkIAEJSEACEpCABCQgAQlIQAISkIAEJCABCUhAAhKQgAQkIAEJSEACEpCABCQgAQlIQAISkMCXT6DfyXzrT/KlrPOtc3R9EpCABCTwigT2v+bCd0c5bIGzbv8lPr9LuuS+JxKleW/kn+LN5X6JY5xy1HOBGcuBDTfx2n4s+cQ4eIE1dL79OtOlSUACEpCABN4egZ+zJL7P+SnOSUecisQ9u8P/3Nq5XIw4ojcNMSXeU5o+pt3TiBDFc5w53sfJW7cr447GLls/41gDY/jO6X6dCWkSkIAEJCCBlyNQ8XqJAw4QrxrCijjW6FviPfMWsWTHibO7RADXOMJ5irdWhZB+jPv9YfRHY/tcl0H5h3rLdtPa260XCUhAAhKQwMsRQFCnAD61MrtBBKsCPc/xpSZvx7KbRRRP8SXOPY7YIo638XXzH3PFKpDr5e5OWBHXaUdjlySwhhprW+L7dbbfqwQkIAEJSOBNEUBQEa9+lrkXVnal9M+c3N4bojoFk3yM/NN2RYD7+6QI5Ic4O9yjsRVkxrAm6tDerzMhTQISkIAEJPA2CfSzzCXL2wsrK2Z3On/9hVit4lfxPaUDbz7tcxxDSJs3hbOxU/orrI1N0Z7rTKomAQlIQAISeLsE2EleM0Tyt952fmj8rHuUN2NLkvtW8Iy3xlGsfV4lIAEJSEACb55A34LtZ7CvvWB2rN3hvvZc1peABCQgAQlIQAISkIAEJCABCUhAAhKQgAQkIAEJSEACEpCABCQgAQlIQAISkIAEJCABCUhAAhKQwNdLgK+08BWbl/pqC6cxcUCEJgEJSEACEvgmCSCoHNDwUl+x4ZCHNa5JQAISkIAEvgkCnJ7EjvIv29PuhZU4/VNoOTBiH9uGX3a6jCGHWlNYe7xh52LMTfwdjRjHHeIYuaf4Eq/Rd4r/0IBXCUhAAhKQwFsigKCxO/0pzpGBHF84hZV7fI1zeAPGyUh/jSOYjN0bMWrhHN5P3hrvYROntM9x6mLk/3Bp3eUx5vstztvIzSOHXGJcP8Y1CUhAAhKQwIsQ6Jm6cxf5lMKnDELk3scrXH9MG+GiNp+1IqI1doz0MT87StpLvLakQWxahbUxxLziSGyeT9zc1q6Yk3eOr3HWeorv50lIk4AEJCABCTyNAKL3Ejs2hAyBWuPsFNm5zh0rbXaM5Pw5vmztNVfyubK7rC1p9KzfxiqW3bEi1rdxhBKbwsr8K8HYTZx5m8eVcevmiLMmAQlIQAISeFME+Jx0CiGftyKmCBpCyO4QI4+da3eS7wjGer27+6UfsaWPXXCFtTticj/GOy+CSX2MGPmMZX6MtXCPqNJXI6ZJQAISkIAE3hwBBAvxwmlPYZ19S/owdpXN50r+NMSv/ewqK6wIJcJJ33nzXL5b4s1nPvI/jBif1WJHP1F31+O/EpCABCQggTdGAHHcC2SX+Lnxjrt2vVbvKP8o9yh2NNaYBCQgAQlIQAISkIAEJCABCUhAAhKQgAQkIAEJSEACEpCABCQgAQlIQAISkIAEJCABCUhAAhKQgAS+HQKc28vXXfhqDIdAfK4xju+h8te6T/1VHL4fy0EUmgQkIAEJSOCLJ4CoLvE/xWn3YIY0H2X9nirC+pTxTLJsY2lrEpCABCQggS+WADtUxJCTkBDU7lg5oAHvr9SkeTFOO+oOtScfHQlr6zDofXye+UsMEW5t2j37mL6jObqe9t/QiJHLbnn+Wg65pzgnPWkSkIAEJCCB35UAooiw8jbsv25tBHbG6edcYOwcp4/jDYlj3K/xuWOlj7d3sds4pzVNo3/+As4U1qM51uR3DUvanZsrtVk/60ZMiSH+XD/GNQlIQAISkMBvEqgQfe7btkeFK1JTGCue5HeujmXOxirCa2JzPCJYIaQ+O8vakkbnbKz1en9tDvpn7l48z+lf4+yST/H9PAlpEpCABCQggV8TQHheYjc2xXC2uwtl5ilk7DIRq+5YrwlrD+vnLVrEbtqSmx7A3/hj5mBN2Id4BRMBpT73HPxP+za+bs7OVZOABCQgAQn8bgSmmM72kbAioggYeYgY7WvCmq77A/fn563EK7rUYCfL27cV1mtz8HYvgomxE64wUwPjr5Fv4uRUgNP8h50y95oEJCABCUjgVQlMMZ3tI2FlIXyWiaD2V2oeElZ21BXiNP/BqE8fzq6ywprm4RwIcPPZNZ/jXS9x1kOOv4ATCJoEJCABCXxZBBC0x9gpSf3Jt8fkz5xrcxzFHxub9W1LQAISkIAEvjgC7CrZiWoSkIAEJCABCUhAAhKQgAQkIAEJSEACEpCABCQgAQlIQAISkIAEJCABCUhAAhKQgAQkIAEJSEACEpDAaxPg9CIObehhC9fm62EOR/0P9R3lH8VYx/SjnJeO8dwfXrqo9SQgAQlI4Nsl0JOO+GoMBy1wgtE146sz5B3ZQ31H+fvYXAdzPPX7r/u6R/ezNic6zZOajvKNSUACEpCABB5NAEGrWHLQAuLKDo42RxGe4uzqsP2ulHOA+ck2asw+jihkDCcq3cRrnIpEPnVnnP65Du4x1rHQiFG/RyNSZ1+b3FOcuWu02YWf4v0+LTV4RsZTc79j/ZgYa3wfx/pcS9rEua/N52/MqwQkIAEJfOMEEDSOA+SK2CE6tNnFsbNjR0cMgVq2di6XYwc53nCNI1pLnDysxx1ypi8xxAyhpk299qd5b10HAkk97rkyBiE9x1kTgkds3a6IJ04MseT6Mc542njXQW1qEGPtiOoa76/wsC527M2nv2s4p30bZyzGeHyNk6NJQAISkMAXTqAv+AjIc6yCh2Dg7Mpq9CGoxBGvzpnmRYD4hZva7EOgurtEyBCq2U/fGp/WdSBe5zgiiFUIiWGtd3d39y99axzRPcVZb+shyhhrWGnE6K9Rb43P9dHX/H2csTBHgOfz51aTgAQkIIEvmQAv7h9f4AGogzBhpziiiCGwiEh/Hm5Je4oMwsWOjRyEcvZRY4ljFS4EjlyEkytCPW2uY8Zbd92C1MOnnXND3XVzdq6sj3lqFcrGmQ/r+pa0++zEee41zvyNz7G05/PnVpOABCQgAQnc7b4qHPBAjD5s14ofsSVekUvz/jNIBBgRmn1Hwrokhzqn+E18bwhd14Fo4VjHcOWt2Qo+/ayTXeptfIrtu9zTzxg+B8WojeAyD/HuZCus1CHOFWv+fK7WpEbz+vyXQf4jAQlIQAISmIIGje7sECGEpr6kPUUGMbvWdySsHYsId2ya91bRas1zek7x/pUybWJYx5OL2HY33LGnxPb1Widdl8+OyV3iFdY07z9Ppq9/Odx109+aMJtrWOjUJCABCUhAAs8lgNA81tYk8tYp1s9tEain2tHcM0YbgeQ6453vKPaYvuZwfajGzLMtAQlIQAISeHEC7CrZNXZX+RKfDz+0SESPuZ4j3g/Vt08CEpCABCQgAQlIQAISkIAEJCABCUhAAhKQgAQkIAEJSEACEpCABCQgAQlIQAISeAEC/U5mS3H/Gn/xSs3b36jN12fOcb6Ww/do+U7qc4w6fN91GjWZh+fk+hrPmrK/sp5G9asOAxKQgAQk8PUQ4K9m+evZadz3cIgZf24bAfutv9TlL4c5dAHRo73En2NHz7KmIPHzduW7qq9h/OVz//r5Mc/+GmuwpgQkIAEJ/M4EENaeeNSp5wEPCOwpPne1iAXi16+ysOtDnH6M094bY8mn1hRWdpKnLZ7LZSz9HNrAmO5Y2WHSXuLU4b62r0GcdZG3xOez5PZia/5dLq1f/mE3yfdrMWpWbGlTq/dpXsSSWJ+fHMZSAwYYfbfx+Z+DuWPtumeMZ4QfNW7iNZ6X+XqKVONeJSABCUjgDRJAAK4JKwKK0PGifopj5PL26s9x+rC2EZEpFPT1VCTGkI8zZ0UWESHGXIyljSC1TR6iRvwcp482dlSDeGuwHtpLfBrr5ZkQsf5H4JQ2uaytYxAy2j9t17K69vyfkgcf1vh+a3PP+Nadz15uPeWJXObj9CuuZdk1UJ/xmgQkIAEJvAKBis1zX2gZf96tjxf4JY748KLec3U/bPfMjSDRt8QRCF70sT/E2W3h5CAq7WMuxnTONW0E6BQnjjF3d4ddR5/1kpB/HqrRNc7cpTfblTVRGwHs2uiqEK/cxJjnh0vr7p/Wfuj55zMyD2wwuHTdzN3d58wnXjFlHAKLMY7/eGgSkIAEJPCKBHhBfokX276wz6XyQl5xO6XNPS/yy9Zec+2Zwt+njQgQwxBhxApHPNZ4xSXNe3E5p42wrZv/mCtWMZ1t1kIcmwJ1VGNJTnPJn/W4x9b4Et8bQsizVkwZWw7kLnH61/j++fuMc32Ty4xTo3XLn+tc6xzLfz54VsbBW5OABCQggTdOgBfsj9sa2WlyjxDwgo51d9rru7vwd71OEdi67i/UpR7Wt1YRkdt4xYi+1pri0jYi1BpToI5qsGZyEaC2l7SnrbnpzpB6WHNPaXcu6nfXeJP2v299XWuvCDJrpRZ5Hb+m3fH0Ee+z83YyNvP7vMQn04opO2ryNQlIQAISeOME2KHxol/vi/dpxGhjiEjzuCIYUwRy+yvrW6wIFWMQl3722lqnxLApLm1fE9ZrNdbUoS7jz/ElPu2Um87LdYmzRt76xmjznAjazMvt4fPvmZRf18064ESto2efO+QlOViZdhxjqVMxJ0eTgAQkIIE3ToAX8b0dxci5Ft+P7z2CcmSfW+exNV6ibuc6qjVjiCD+uXaNyVGdOd9RvzEJSEACEpDAV0OAHetThPWrAeCDSEACEpCABCQgAQlIQAISkIAEJCABCUhAAhKQgAQkIAEJSEACEpCABCQgAQlIQAISkIAEJCABCUhAAhKQgAQkIAEJSEACEpCABCQgAQlIQAISkIAEJCABCUhAAhKQgAQkIAEJSEACEpCABCQgAQlIQAISkIAEJCABCUhAAhKQgAQkIAEJSEACEpCABCQgAQlIQAISkIAEJCABCUhAAhKQgAQkIAEJSEACEpCABCQgAQlIQAISkIAEJCABCUhAAhKQgAQkIAEJSEACEpCABCQgAQlIQAISkIAEJCABCUhAAhKQgAQkIAEJSEACEpCABCQgAQlIQAISkIAEJCABCUjg/4XA/wFCRhWrhsCgBQAAAABJRU5ErkJggg=="
    }
   },
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "·\tHandling Exceptions\n",
    "·\ttry-except\n",
    "·\telse clause\n",
    "·\tfinally clause\n",
    "·\tRaising Exceptions\n",
    "·\tUser-defined Exceptions\n",
    "![image.png](attachment:image.png)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Errors and Exceptions"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Python provides two very important features to handle any unexpected error in your Python programs and to add debugging capabilities in them"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "1. Syntax Error\n",
    "2. Run time error"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Exceptions versus Syntax Errors"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "ename": "SyntaxError",
     "evalue": "invalid syntax (<ipython-input-2-45b2a957bde4>, line 1)",
     "output_type": "error",
     "traceback": [
      "\u001b[0;36m  File \u001b[0;32m\"<ipython-input-2-45b2a957bde4>\"\u001b[0;36m, line \u001b[0;32m1\u001b[0m\n\u001b[0;31m    print( 0 / 0 ))\u001b[0m\n\u001b[0m                  ^\u001b[0m\n\u001b[0;31mSyntaxError\u001b[0m\u001b[0;31m:\u001b[0m invalid syntax\n"
     ]
    }
   ],
   "source": [
    "print( 0 / 0 ))\n",
    "  File \"<stdin>\", line 1\n",
    "    print( 0 / 0 ))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "ename": "SyntaxError",
     "evalue": "invalid syntax (<ipython-input-7-e68cc763c3ad>, line 1)",
     "output_type": "error",
     "traceback": [
      "\u001b[0;36m  File \u001b[0;32m\"<ipython-input-7-e68cc763c3ad>\"\u001b[0;36m, line \u001b[0;32m1\u001b[0m\n\u001b[0;31m    print( Hello world)\u001b[0m\n\u001b[0m                     ^\u001b[0m\n\u001b[0;31mSyntaxError\u001b[0m\u001b[0;31m:\u001b[0m invalid syntax\n"
     ]
    }
   ],
   "source": [
    "print(Hello world)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "ename": "SyntaxError",
     "evalue": "Missing parentheses in call to 'print'. Did you mean print(Hello world)? (<ipython-input-9-0faf766ec3b9>, line 1)",
     "output_type": "error",
     "traceback": [
      "\u001b[0;36m  File \u001b[0;32m\"<ipython-input-9-0faf766ec3b9>\"\u001b[0;36m, line \u001b[0;32m1\u001b[0m\n\u001b[0;31m    print Hello world\u001b[0m\n\u001b[0m              ^\u001b[0m\n\u001b[0;31mSyntaxError\u001b[0m\u001b[0;31m:\u001b[0m Missing parentheses in call to 'print'. Did you mean print(Hello world)?\n"
     ]
    }
   ],
   "source": [
    "print Hello world"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Hello world\n"
     ]
    }
   ],
   "source": [
    "print(\"Hello world\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "The arrow indicates where the parser ran into the syntax error. In this example, there was one bracket too many. Remove it and run your code again:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "ename": "ZeroDivisionError",
     "evalue": "division by zero",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mZeroDivisionError\u001b[0m                         Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-4-b7f65c155a3b>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m \u001b[0;36m0\u001b[0m \u001b[0;34m/\u001b[0m \u001b[0;36m0\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;31mZeroDivisionError\u001b[0m: division by zero"
     ]
    }
   ],
   "source": [
    "print( 0 / 0)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Runtime Error"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Runtime errors are the errors which happen while the program is running. Note that runtime errors do not indicate there is a problem in the structure (or syntax) of the program. When runtime errors occur Python interpreter perfectly understands your statement but it just can’t execute it. However, Syntax Errors occurs due to the incorrect structure of the program. Both types of errors halt the execution of the program as soon as they are encountered and displays an error message (or traceback) explaining the probable cause of the problem.\n",
    "\n",
    "The following are some examples of runtime errors."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "enter first number: 34\n"
     ]
    }
   ],
   "source": [
    "x = int(input('enter first number: '))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "enter first number: 0\n"
     ]
    }
   ],
   "source": [
    "y = int(input('enter first number: '))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {},
   "outputs": [
    {
     "ename": "ZeroDivisionError",
     "evalue": "division by zero",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mZeroDivisionError\u001b[0m                         Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-24-e62e291e00b5>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'result is'\u001b[0m \u001b[0;34m,\u001b[0m \u001b[0mx\u001b[0m\u001b[0;34m/\u001b[0m\u001b[0my\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;31mZeroDivisionError\u001b[0m: division by zero"
     ]
    }
   ],
   "source": [
    "print('result is' , x/y)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "enter first number: test\n"
     ]
    },
    {
     "ename": "ValueError",
     "evalue": "invalid literal for int() with base 10: 'test'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mValueError\u001b[0m                                Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-25-0f926b01ce5e>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mx\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0minput\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'enter first number: '\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      2\u001b[0m \u001b[0my\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0minput\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'enter first number: '\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      3\u001b[0m \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'result is'\u001b[0m \u001b[0;34m,\u001b[0m \u001b[0mx\u001b[0m\u001b[0;34m/\u001b[0m\u001b[0my\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mValueError\u001b[0m: invalid literal for int() with base 10: 'test'"
     ]
    }
   ],
   "source": [
    "x = int(input('enter first number: '))\n",
    "y = int(input('enter first number: '))\n",
    "print('result is' , x/y)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### ZeroDivision Error\n",
    "#### Value Error"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "metadata": {},
   "outputs": [
    {
     "ename": "FileNotFoundError",
     "evalue": "[Errno 2] File data.csv does not exist: 'data.csv'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mFileNotFoundError\u001b[0m                         Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-30-bc3ad256009a>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mdata\u001b[0m \u001b[0;34m=\u001b[0m\u001b[0mpd\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mread_csv\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"data.csv\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;32m~/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py\u001b[0m in \u001b[0;36mparser_f\u001b[0;34m(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, dialect, error_bad_lines, warn_bad_lines, delim_whitespace, low_memory, memory_map, float_precision)\u001b[0m\n\u001b[1;32m    674\u001b[0m         )\n\u001b[1;32m    675\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 676\u001b[0;31m         \u001b[0;32mreturn\u001b[0m \u001b[0m_read\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mfilepath_or_buffer\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mkwds\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    677\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    678\u001b[0m     \u001b[0mparser_f\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m__name__\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mname\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py\u001b[0m in \u001b[0;36m_read\u001b[0;34m(filepath_or_buffer, kwds)\u001b[0m\n\u001b[1;32m    446\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    447\u001b[0m     \u001b[0;31m# Create the parser.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 448\u001b[0;31m     \u001b[0mparser\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mTextFileReader\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mfp_or_buf\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwds\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    449\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    450\u001b[0m     \u001b[0;32mif\u001b[0m \u001b[0mchunksize\u001b[0m \u001b[0;32mor\u001b[0m \u001b[0miterator\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py\u001b[0m in \u001b[0;36m__init__\u001b[0;34m(self, f, engine, **kwds)\u001b[0m\n\u001b[1;32m    878\u001b[0m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0moptions\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m\"has_index_names\"\u001b[0m\u001b[0;34m]\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mkwds\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m\"has_index_names\"\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    879\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 880\u001b[0;31m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_make_engine\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mengine\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    881\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    882\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0mclose\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py\u001b[0m in \u001b[0;36m_make_engine\u001b[0;34m(self, engine)\u001b[0m\n\u001b[1;32m   1112\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0m_make_engine\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mengine\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m\"c\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1113\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mengine\u001b[0m \u001b[0;34m==\u001b[0m \u001b[0;34m\"c\"\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1114\u001b[0;31m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_engine\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mCParserWrapper\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mf\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0moptions\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1115\u001b[0m         \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1116\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0mengine\u001b[0m \u001b[0;34m==\u001b[0m \u001b[0;34m\"python\"\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py\u001b[0m in \u001b[0;36m__init__\u001b[0;34m(self, src, **kwds)\u001b[0m\n\u001b[1;32m   1889\u001b[0m         \u001b[0mkwds\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m\"usecols\"\u001b[0m\u001b[0;34m]\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0musecols\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1890\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1891\u001b[0;31m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_reader\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mparsers\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mTextReader\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0msrc\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwds\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1892\u001b[0m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0munnamed_cols\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_reader\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0munnamed_cols\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1893\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32mpandas/_libs/parsers.pyx\u001b[0m in \u001b[0;36mpandas._libs.parsers.TextReader.__cinit__\u001b[0;34m()\u001b[0m\n",
      "\u001b[0;32mpandas/_libs/parsers.pyx\u001b[0m in \u001b[0;36mpandas._libs.parsers.TextReader._setup_parser_source\u001b[0;34m()\u001b[0m\n",
      "\u001b[0;31mFileNotFoundError\u001b[0m: [Errno 2] File data.csv does not exist: 'data.csv'"
     ]
    }
   ],
   "source": [
    "data =pd.read_csv(\"data.csv\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### TypeError: unsupported operand type(s) for +: 'int' and 'str'\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "ename": "TypeError",
     "evalue": "unsupported operand type(s) for +: 'int' and 'str'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-1-db2f06a66b01>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0;36m10\u001b[0m \u001b[0;34m+\u001b[0m \u001b[0;34m\"12\"\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;31mTypeError\u001b[0m: unsupported operand type(s) for +: 'int' and 'str'"
     ]
    }
   ],
   "source": [
    "10 + \"12\""
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Trying to access an element at an invalid index. :: IndexError: list index out of range\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "list1 = [11, 3, 99, 15]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "ename": "IndexError",
     "evalue": "list index out of range",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mIndexError\u001b[0m                                Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-4-1a2e5d318e75>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mlist1\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;36m10\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;31mIndexError\u001b[0m: list index out of range"
     ]
    }
   ],
   "source": [
    "list1[10]"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Opening a file in read mode which doesn’t exist."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "ename": "FileNotFoundError",
     "evalue": "[Errno 2] No such file or directory: 'filedoesntexists.txt'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mFileNotFoundError\u001b[0m                         Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-5-3f0fedade735>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mf\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mopen\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"filedoesntexists.txt\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m\"r\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;31mFileNotFoundError\u001b[0m: [Errno 2] No such file or directory: 'filedoesntexists.txt'"
     ]
    }
   ],
   "source": [
    "f = open(\"filedoesntexists.txt\", \"r\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### try-except statement\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "##### syntax"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "try:\n",
    "    # try block\n",
    "    # write code that might raise an exception here\n",
    "    <statement_1>\n",
    "    <statement_2>\n",
    "except ExceptionType:\n",
    "    # except block\n",
    "    # handle exception here\n",
    "    <handler>"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "When an exception occurs in the try block, execution of the rest of the statements in the try block is skipped. If the exception raised matches the exception type in the except clause, the corresponding handler is executed.\n",
    "\n",
    "If the exception raised in the try block doesn’t matches with the exception type specified in the except clause the program halts with a traceback.\n",
    "\n",
    "On the other hand, If no exception is raised in the try block, the except clause is skipped.\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Enter a number: 0\n",
      "Exception Handler for ZeroDivisionError\n",
      "We cant divide a number by 0\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    num =  int(input(\"Enter a number: \"))\n",
    "    result = 10/num\n",
    "    print(\"Result: \", result)    \n",
    " \n",
    "except ZeroDivisionError:\n",
    "    print(\"Exception Handler for ZeroDivisionError\")\n",
    "    print(\"We cant divide a number by 0\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "In this example, the try block in line 3 raises a ZeroDivisionError. When an exception occurs Python looks for the except clause with the matching exception type. In this case, it finds one and runs the exception handler code in that block. Notice that because an exception is raised in line 3, the execution of reset of the statements in the try block is skipped.\n",
    "\n",
    "Run the program again but this time enter a string instead of a number:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Enter a number: sudhanshu\n"
     ]
    },
    {
     "ename": "ValueError",
     "evalue": "invalid literal for int() with base 10: 'sudhanshu'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mValueError\u001b[0m                                Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-10-b1346ce952d1>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 2\u001b[0;31m     \u001b[0mnum\u001b[0m \u001b[0;34m=\u001b[0m  \u001b[0mint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0minput\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"Enter a number: \"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      3\u001b[0m     \u001b[0mresult\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;36m10\u001b[0m\u001b[0;34m/\u001b[0m\u001b[0mnum\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      4\u001b[0m     \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"Result: \"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mresult\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mValueError\u001b[0m: invalid literal for int() with base 10: 'sudhanshu'"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    num =  int(input(\"Enter a number: \"))\n",
    "    result = 10/num\n",
    "    print(\"Result: \", result)    \n",
    " \n",
    "except ZeroDivisionError:\n",
    "    print(\"Exception Handler for ZeroDivisionError\")\n",
    "    print(\"We cant divide a number by 0\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "This time our program crashes with the ValueError exception. The problem is that the built-in int() only works with strings that contain numbers only, if you pass a string containing non-numeric character it will throw ValueError exception"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Handling Multiple Exceptions"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "We can add as many except clause as we want to handle different types of exceptions. The general format of such a try-except statement is as follows:"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "try:\n",
    "    # try block\n",
    "    # write code that might raise an exception here\n",
    "    <statement_1>\n",
    "    <statement_2>\n",
    "except <ExceptionType1>:\n",
    "    # except block\n",
    "    # handle ExceptionType1 here\n",
    "    <handler>\n",
    "except <ExceptionType2>:\n",
    "    # except block\n",
    "    # handle ExceptionType2 here\n",
    "    <handler>\n",
    "except <ExceptionType3>:\n",
    "    # except block\n",
    "    # handle ExceptionType3 here\n",
    "    <handler>\n",
    "except:\n",
    "    # handle any type of exception here\n",
    "    <handler>"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Here is how it works:\n",
    "\n",
    "When an exception occurs, Python matches the exception raised against the every except clause sequentially. If a match is found then the handler in the corresponding except clause is executed and rest of the of the except clauses are skipped.\n",
    "\n",
    "In case the exception raised doesn’t match any except clause before the last except clause (line 18), then the handler in the last except clause is executed. Note that the last except clause doesn’t have any exception type in front of it, as a result, it can catch any type of exception. Of course, this last except clause is entirely optional but we commonly use it as a last resort to catch the unexpected errors and thus prevent the program from crashing."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "The following program demonstrates how to use multiple except clauses.\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Enter a num1: 11\n",
      "Enter a num2: 0\n",
      "\n",
      "Exception Handler for ZeroDivisionError\n",
      "We cant divide a number by 0\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    num1 = int(input(\"Enter a num1: \"))\n",
    "    num2 = int(input(\"Enter a num2: \"))\n",
    " \n",
    "    result = num1 / num2\n",
    "    print(\"Result: \", result)\n",
    " \n",
    "except ZeroDivisionError:\n",
    "    print(\"\\nException Handler for ZeroDivisionError\")\n",
    "    print(\"We cant divide a number by 0\")\n",
    " \n",
    "except ValueError:\n",
    "    print(\"\\nException Handler for ValueError\")\n",
    "    print(\"Invalid input: Only integers are allowed\")\n",
    " \n",
    "except:\n",
    "    print(\"\\nSome unexpected error occurred\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Enter a num1: 100\n",
    "Enter a num2: a13"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Enter a num1: 100\n",
      "Enter a num2: a13\n",
      "\n",
      "Exception Handler for ValueError\n",
      "Invalid input: Only integers are allowed\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    num1 = int(input(\"Enter a num1: \"))\n",
    "    num2 = int(input(\"Enter a num2: \"))\n",
    " \n",
    "    result = num1 / num2\n",
    "    print(\"Result: \", result)\n",
    " \n",
    "except ZeroDivisionError:\n",
    "    print(\"\\nException Handler for ZeroDivisionError\")\n",
    "    print(\"We cant divide a number by 0\")\n",
    " \n",
    "except ValueError:\n",
    "    print(\"\\nException Handler for ValueError\")\n",
    "    print(\"Invalid input: Only integers are allowed\")\n",
    " \n",
    "except:\n",
    "    print(\"\\nSome unexpected error occurred\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "below is the program which asks the user to enter the filename and then prints the content of the file to the console"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Enter file name: /home/test.xlsx/passwd\n",
      "File not found\n"
     ]
    }
   ],
   "source": [
    "filename = input(\"Enter file name: \")\n",
    " \n",
    "try:\n",
    "    f = open(filename, \"r\")\n",
    " \n",
    "    for line in f:\n",
    "        print(line, end=\"\")\n",
    " \n",
    "    f.close()\n",
    " \n",
    "except FileNotFoundError:\n",
    "    print(\"File not found\")\n",
    " \n",
    "except PermissionError:\n",
    "    print(\"You don't have the permission to read the file\")\n",
    " \n",
    "except:\n",
    "    print(\"Unexpected error while reading the file\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### The else and finally clause"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "A try-except statement can also have an optional else clause which only gets executed when no exception is raised. The general format of try-except statement with else clause is as follows:\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "try:    \n",
    "    #<statement_1>\n",
    "    #<statement_2>\n",
    "    \n",
    "except #<ExceptionType1>:    \n",
    "    #<handler>\n",
    "except #<ExceptionType2>:    \n",
    "    #<handler>\n",
    "else:\n",
    "    # else block only gets executed\n",
    "    # when no exception is raised in the try block\n",
    "    <statement>\n",
    "    <statement>"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Here is a rewrite of the above program using else clause."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Enter file name: test.xlsx\n",
      "File not found\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "filename = input(\"Enter file name: \")\n",
    " \n",
    "try:\n",
    "    f = open(filename, \"r\")\n",
    " \n",
    "    for line in f:\n",
    "        print(line, end=\"\")\n",
    " \n",
    "    f.close()\n",
    " \n",
    "except FileNotFoundError:\n",
    "    print(\"File not found\")\n",
    " \n",
    "except PermissionError:\n",
    "    print(\"You don't have the permission to read the file\")\n",
    " \n",
    "except FileExistsError:\n",
    "    print(\"You don't have the permission to read the file\")\n",
    " \n",
    "except:\n",
    "    print(\"Unexpected error while reading the file\")\n",
    " \n",
    "else:\n",
    "    print(\"Program ran without any problem\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Again run the program but this time enter a file which does exist and you have the permission to access it.\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "As expected, the statement in the else clause is executed this time. The else clause is usually used to write code which we want to run after the code in the try block ran successfully.\n",
    "\n",
    "Similarly, we can have a finally clause after all except clauses. The statements under the finally clause will always execute irrespective of whether the exception is raised or not. Its general form is as follows:"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "try:    \n",
    "    #<statement_1>\n",
    "    #<statement_2>\n",
    "except #<ExceptionType1>:    \n",
    "    #<handler>\n",
    "except #<ExceptionType2>:    \n",
    "    #<handler>\n",
    "finally:\n",
    "    # statements here will always\n",
    "    # execute no matter what\n",
    "    #<statement>\n",
    "    #<statement>"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "The finally clause is commonly used to define clean up actions which must be performed under any circumstance. If try-except statement has an else clause then finally clause must appear after it.\n",
    "\n",
    "The following program shows finally clause in action."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Enter file name: test.xlsx\n",
      "File not found\n",
      "finally clause: This will always execute\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "filename = input(\"Enter file name: \")\n",
    " \n",
    "try:\n",
    "    f = open(filename, \"r\")\n",
    " \n",
    "    for line in f:\n",
    "        print(line, end=\"\")\n",
    " \n",
    "    f.close()\n",
    " \n",
    "except FileNotFoundError:\n",
    "    print(\"File not found\")\n",
    " \n",
    "except PermissionError:\n",
    "    print(\"You don't have the permission to read the file\")\n",
    " \n",
    "except FileExistsError:\n",
    "    print(\"You don't have the permission to read the file\")\n",
    " \n",
    "except:\n",
    "    print(\"Unexpected error while reading the file\")\n",
    " \n",
    "else:\n",
    "    print(\"\\nProgram ran without any problem\")\n",
    " \n",
    "finally:\n",
    "    print(\"finally clause: This will always execute\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Exceptions Propagation and Raising Exceptions\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "In the earlier few sections, we have learned how to deal with exceptions using try-except statement. In this section, we will discuss who throws an exception, how to create an exception and how they propagate.\n",
    "\n",
    "An exception is simply an object raised by a function signaling that something unexpected has happened which the function itself can’t handle. A function raises an exception by creating an exception object from an appropriate class and then throws the exception to the calling code using the raise keyword as follows:\n",
    "\n",
    "1\n",
    "raise SomeExceptionClas(\"Error message describing cause of the error\")\n",
    "We can raise exceptions from our own functions by creating an instance of RuntimeError() as follows:\n",
    "\n",
    "1\n",
    "raise RuntimeError(\"Someting went very wrong\")\n",
    "When an exception is raised inside a function and is not caught there, it is automatically propagated to the calling function (and any function up in the stack), until it is caught by try-except statement in some calling function. If the exception reaches the main module and still not handled, the program terminates with an error message.\n",
    "\n",
    "Let’s take an example.\n",
    "\n",
    "Suppose we are creating a function to calculate factorial of a number. As factorial is only valid for positive integers, passing data of any other type would render the function useless. We can prevent this by checking the type of argument and raising an exception if the argument is not a positive integer. Here is the complete code."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Factorial of 4 is: 24\n",
      "Invalid Input\n"
     ]
    }
   ],
   "source": [
    "def factorial(n):\n",
    "    if  not isinstance(n, int):\n",
    "        raise RuntimeError(\"Argument must be int\")\n",
    " \n",
    "    if n < 0:\n",
    "        raise RuntimeError(\"Argument must be >= 0\")\n",
    " \n",
    "    f = 1\n",
    "    for i in range(n):\n",
    "        f *= n\n",
    "        n -= 1\n",
    " \n",
    "    return f\n",
    " \n",
    "try:\n",
    "    print(\"Factorial of 4 is:\", factorial(4))\n",
    "    print(\"Factorial of 12 is:\", factorial(\"12\"))\n",
    "except RuntimeError:\n",
    "    print(\"Invalid Input\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Notice that when factorial() function is called with a string argument (line 17), a runtime exception is raised in line 3. As factorial() function is not handling the exception, the raised exception is propagated back to the main module where it is caught by the except clause in line 18.\n",
    "\n",
    "Note that in the above example we have coded try-except statement outside the factorial() function but we could have easily done the same inside the factorial() function as follows."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Factorial of 4 is: 24\n",
      "Factorial of 12 is: Invalid Input\n"
     ]
    }
   ],
   "source": [
    "def factorial(n):\n",
    " \n",
    "    try:\n",
    "        if not isinstance(n, int):\n",
    "            raise RuntimeError(\"Argument must be int\")\n",
    " \n",
    "        if n < 0:\n",
    "            raise RuntimeError(\"Argument must be >= 0\")\n",
    " \n",
    "        f = 1\n",
    "        for i in range(n):\n",
    "            f *= n\n",
    "            n -= 1\n",
    " \n",
    "        return f\n",
    " \n",
    "    except RuntimeError:\n",
    "        return  \"Invalid Input\"\n",
    " \n",
    "print(\"Factorial of 4 is:\", factorial(4))\n",
    "print(\"Factorial of 12 is:\", factorial(\"12\"))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "However, this is not recommended. Generally, the called function throws an exception to the caller and it’s the duty of the calling code to handle the exception. This approach allows us to handle exceptions in different ways, for example, in one case we show an error message to the user while in other we silently log the problem. If we were handling exceptions in the called function, then we would have to update the function every time a new behavior is required. In addition to that, all the functions in the Python standard library also conform to this behavior. The library function only detects the problem and raises an exception and the client decide what it needs to be done to handle those errors.\n",
    "\n",
    "Now Let’s see what happens when an exception is raised in a deeply nested function call. Recall that if an exception is raised inside the function and is not caught by the function itself, it is passed to its caller. This process repeats until it is caught by some calling function down in the stack. Consider the following example."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "metadata": {},
   "outputs": [
    {
     "ename": "IndentationError",
     "evalue": "unindent does not match any outer indentation level (<tokenize>, line 37)",
     "output_type": "error",
     "traceback": [
      "\u001b[0;36m  File \u001b[0;32m\"<tokenize>\"\u001b[0;36m, line \u001b[0;32m37\u001b[0m\n\u001b[0;31m    statement2\u001b[0m\n\u001b[0m    ^\u001b[0m\n\u001b[0;31mIndentationError\u001b[0m\u001b[0;31m:\u001b[0m unindent does not match any outer indentation level\n"
     ]
    }
   ],
   "source": [
    "def function3():\n",
    "    try:\n",
    " \n",
    "        ...\n",
    "        raise SomeException()\n",
    "    statement7\n",
    "    except ExceptionType4:\n",
    "        handler\n",
    "    statement8\n",
    " \n",
    " \n",
    "def function2():\n",
    "    try:\n",
    "        ...\n",
    "        function3()\n",
    "        statement5\n",
    "    except ExceptionType3:\n",
    "        handler\n",
    "    statement6\n",
    " \n",
    "def function1():\n",
    "    try:\n",
    "        ...\n",
    "        function2()\n",
    "        statement3\n",
    "    except ExceptionType2:\n",
    "        handler\n",
    "    statement4\n",
    " \n",
    "def main():\n",
    "    try:\n",
    "        ...\n",
    "        function1()\n",
    "        statement1\n",
    "    except ExceptionType1:\n",
    "        handler\n",
    "     statement2\n",
    "    \n",
    "main()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "The program execution starts by calling the main() function. The main() function then invokes function1(), function1() invokes function2(), finally function2() invokes function3(). Let’s assume function3() can raise different types of exceptions. Now consider the following cases.\n",
    "\n",
    "If the exception is of type ExceptionType4, statement7 is skipped and the except clause in line 7 catches it. The execution of function3() proceeds as usual and statement8 is executed.\n",
    "If exception is of type ExceptionType3, the execution of function3() is aborted (as there is no matching except clause to handle the raised exception) and the control is transferred to the caller i.e function2() where ExceptionType3 is handled by the except clause in line 17. The statement5 in function2() is skipped and statement6 is executed.\n",
    "\n",
    "If the exception is of type ExceptionType2, function3() is aborted and the control is transferred to the function2(). As function2() doesn’t have any matching except clause to catch the exception, its execution is aborted and control transferred to the function1() where the exception is caught by the except clause in line 26. The statement3 in function1() is skipped and statement4 is executed.\n",
    "If the exception is of type ExceptionType1, then control is transferred to the function main() (as function3(), function2() and function1() doesn’t have matching except clause to handle the exception) where the exception is handled by except clause in line 35. The statement1 in main() is skipped and statement2 is executed.\n",
    "If the exception is of type ExceptionType0. As none of the available functions have the ability to handle this exception, the program terminates with an error message."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.4"
  },
  "widgets": {
   "application/vnd.jupyter.widget-state+json": {
    "state": {},
    "version_major": 2,
    "version_minor": 0
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
